# Get Golang 1.19.4
FROM golang:1.19.4-bullseye

# Get Go User Service
RUN go install github.com/e-inwork-com/go-team-indexing-service/cmd@latest

# Expose port
EXPOSE 5001

# Run Go User Service
CMD ["cmd"]
